# Development override for docker-compose
version: '3.8'

services:
  clycites-auth:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "5000:5000"
      - "9229:9229"  # Debug port

  # Enable MongoDB Express for development
  mongo-express:
    profiles: []  # Remove profile to enable by default in dev

  # Development nginx with simpler config
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"  # Different port for dev
